#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

MODEL_PATH="${MODEL_PATH:-/home/jovyan/data/Scale-RAE-Qwen1.5B_DiT2.4B}"
OUTPUT_DIR="${OUTPUT_DIR:-/home/jovyan/AURORA/checkpoints/aurora_refcoco_dual1024_slot48_pair4_reg64_recon_cosmin_stage1_fp32}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-aurora_refcoco_dual1024_slot48_pair4_reg64_recon_cosmin_stage1_fp32}"
RESUME_FROM_CHECKPOINT="${RESUME_FROM_CHECKPOINT:-}"

NUM_GPUS="${NUM_GPUS:-2}"
MASTER_PORT="${MASTER_PORT:-29631}"

MAX_STEPS="${MAX_STEPS:-40000}"
NUM_TRAIN_EPOCHS="${NUM_TRAIN_EPOCHS:-1}"
PER_DEVICE_TRAIN_BATCH_SIZE="${PER_DEVICE_TRAIN_BATCH_SIZE:-16}"
PER_DEVICE_EVAL_BATCH_SIZE="${PER_DEVICE_EVAL_BATCH_SIZE:-4}"
GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS:-1}"

LOGGING_STEPS="${LOGGING_STEPS:-10}"
EVAL_STEPS="${EVAL_STEPS:-500}"
SAVE_STEPS="${SAVE_STEPS:-1000}"
DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS:-4}"

REPORT_TO="${REPORT_TO:-wandb}"
BF16="${BF16:-False}"
TF32="${TF32:-True}"

LEARNING_RATE="${LEARNING_RATE:-5e-5}"
DIFF_HEAD_LR="${DIFF_HEAD_LR:-3e-5}"
WARMUP_RATIO="${WARMUP_RATIO:-0.05}"
LR_SCHEDULER_TYPE="${LR_SCHEDULER_TYPE:-cosine}"
CAPTIONSLOT_LATENT_QUERY_LR="${CAPTIONSLOT_LATENT_QUERY_LR:-}"
GRADIENT_CHECKPOINTING="${GRADIENT_CHECKPOINTING:-False}"

VISION_TOWER_AUX_LIST="${VISION_TOWER_AUX_LIST:-[\"google/siglip2-so400m-patch16-512\",\"google/siglip2-so400m-patch14-224\"]}"
VISION_TOWER_AUX_TOKEN_LEN_LIST="${VISION_TOWER_AUX_TOKEN_LEN_LIST:-[1024,256]}"
IMAGE_FEATURE_TOKEN_LEN="${IMAGE_FEATURE_TOKEN_LEN:-1024}"
DIFFUSION_TARGET_TOKEN_LEN="${DIFFUSION_TARGET_TOKEN_LEN:-256}"

CAPTIONSLOT_TRAINING_STAGE="${CAPTIONSLOT_TRAINING_STAGE:-1}"
CAPTIONSLOT_CONTROL_MODE="${CAPTIONSLOT_CONTROL_MODE:-slots}"
CAPTIONSLOT_MAX_SLOTS="${CAPTIONSLOT_MAX_SLOTS:-48}"
CAPTIONSLOT_SLOTS_PER_OBJECT="${CAPTIONSLOT_SLOTS_PER_OBJECT:-4}"
CAPTIONSLOT_N_REGISTER="${CAPTIONSLOT_N_REGISTER:-64}"
CAPTIONSLOT_CMD_LENGTH="${CAPTIONSLOT_CMD_LENGTH:-8}"

CAPTIONSLOT_RECON_LOSS_WEIGHT="${CAPTIONSLOT_RECON_LOSS_WEIGHT:-1.0}"
CAPTIONSLOT_MASK_BCE_LOSS_WEIGHT="${CAPTIONSLOT_MASK_BCE_LOSS_WEIGHT:-1.0}"
CAPTIONSLOT_MASK_DICE_LOSS_WEIGHT="${CAPTIONSLOT_MASK_DICE_LOSS_WEIGHT:-1.0}"
CAPTIONSLOT_CAPTION_LOSS_WEIGHT="${CAPTIONSLOT_CAPTION_LOSS_WEIGHT:-0.0}"
CAPTIONSLOT_DIVERSITY_LOSS_WEIGHT="${CAPTIONSLOT_DIVERSITY_LOSS_WEIGHT:-0.0}"

CAPTIONSLOT_TRAIN_LATENT_QUERIES="${CAPTIONSLOT_TRAIN_LATENT_QUERIES:-False}"
CAPTIONSLOT_ATTENTION_USE_LAYERNORM="${CAPTIONSLOT_ATTENTION_USE_LAYERNORM:-True}"
CAPTIONSLOT_ATTENTION_TEMPERATURE="${CAPTIONSLOT_ATTENTION_TEMPERATURE:-1.0}"
CAPTIONSLOT_PRIOR_BIAS_SCALE="${CAPTIONSLOT_PRIOR_BIAS_SCALE:-0.0}"

CAPTIONSLOT_ADD_CROSS_ATTENTION="${CAPTIONSLOT_ADD_CROSS_ATTENTION:-False}"
CAPTIONSLOT_CROSS_ATTENTION_START_BLOCK="${CAPTIONSLOT_CROSS_ATTENTION_START_BLOCK:-8}"
CAPTIONSLOT_CROSS_ATTENTION_EVERY_N_BLOCKS="${CAPTIONSLOT_CROSS_ATTENTION_EVERY_N_BLOCKS:-4}"
CAPTIONSLOT_CROSS_ATTENTION_INCLUDE_REGISTERS="${CAPTIONSLOT_CROSS_ATTENTION_INCLUDE_REGISTERS:-True}"
CAPTIONSLOT_USE_WSD_SCHEDULE="${CAPTIONSLOT_USE_WSD_SCHEDULE:-False}"
CAPTIONSLOT_WSD_DECAY_FRACTION="${CAPTIONSLOT_WSD_DECAY_FRACTION:-0.10}"
CAPTIONSLOT_USE_COSINE_MIN_LR_SCHEDULE="${CAPTIONSLOT_USE_COSINE_MIN_LR_SCHEDULE:-True}"
CAPTIONSLOT_MIN_LR_RATIO="${CAPTIONSLOT_MIN_LR_RATIO:-0.10}"

CAPTIONSLOT_EVAL_NUM_IMAGES="${CAPTIONSLOT_EVAL_NUM_IMAGES:-64}"
CAPTIONSLOT_COCO_ROOT="${CAPTIONSLOT_COCO_ROOT:-/home/jovyan/data/coco}"
CAPTIONSLOT_DATASETS="${CAPTIONSLOT_DATASETS:-refcoco,refcoco+,refcocog}"
CAPTIONSLOT_TRAIN_SPLITS="${CAPTIONSLOT_TRAIN_SPLITS:-train}"
CAPTIONSLOT_EVAL_SPLITS="${CAPTIONSLOT_EVAL_SPLITS:-val}"
CAPTIONSLOT_MIN_AREA="${CAPTIONSLOT_MIN_AREA:-0}"
MAX_CAPTION_TOKENS="${MAX_CAPTION_TOKENS:-192}"
MODEL_MAX_LENGTH="${MODEL_MAX_LENGTH:-2048}"

DIFFUSION_NORM_STATS_PATH="${DIFFUSION_NORM_STATS_PATH:-/home/jovyan/data/siglip2_bn_stats.pt}"

mkdir -p "${OUTPUT_DIR}"

env \
  CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}" \
  MODEL_PATH="${MODEL_PATH}" \
  OUTPUT_DIR="${OUTPUT_DIR}" \
  EXPERIMENT_NAME="${EXPERIMENT_NAME}" \
  RESUME_FROM_CHECKPOINT="${RESUME_FROM_CHECKPOINT}" \
  NUM_GPUS="${NUM_GPUS}" \
  MASTER_PORT="${MASTER_PORT}" \
  MAX_STEPS="${MAX_STEPS}" \
  NUM_TRAIN_EPOCHS="${NUM_TRAIN_EPOCHS}" \
  PER_DEVICE_TRAIN_BATCH_SIZE="${PER_DEVICE_TRAIN_BATCH_SIZE}" \
  PER_DEVICE_EVAL_BATCH_SIZE="${PER_DEVICE_EVAL_BATCH_SIZE}" \
  GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS}" \
  LOGGING_STEPS="${LOGGING_STEPS}" \
  EVAL_STEPS="${EVAL_STEPS}" \
  SAVE_STEPS="${SAVE_STEPS}" \
  DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS}" \
  REPORT_TO="${REPORT_TO}" \
  BF16="${BF16}" \
  TF32="${TF32}" \
  LEARNING_RATE="${LEARNING_RATE}" \
  DIFF_HEAD_LR="${DIFF_HEAD_LR}" \
  WARMUP_RATIO="${WARMUP_RATIO}" \
  LR_SCHEDULER_TYPE="${LR_SCHEDULER_TYPE}" \
  CAPTIONSLOT_LATENT_QUERY_LR="${CAPTIONSLOT_LATENT_QUERY_LR}" \
  GRADIENT_CHECKPOINTING="${GRADIENT_CHECKPOINTING}" \
  VISION_TOWER_AUX_LIST="${VISION_TOWER_AUX_LIST}" \
  VISION_TOWER_AUX_TOKEN_LEN_LIST="${VISION_TOWER_AUX_TOKEN_LEN_LIST}" \
  IMAGE_FEATURE_TOKEN_LEN="${IMAGE_FEATURE_TOKEN_LEN}" \
  DIFFUSION_TARGET_TOKEN_LEN="${DIFFUSION_TARGET_TOKEN_LEN}" \
  CAPTIONSLOT_TRAINING_STAGE="${CAPTIONSLOT_TRAINING_STAGE}" \
  CAPTIONSLOT_CONTROL_MODE="${CAPTIONSLOT_CONTROL_MODE}" \
  CAPTIONSLOT_MAX_SLOTS="${CAPTIONSLOT_MAX_SLOTS}" \
  CAPTIONSLOT_SLOTS_PER_OBJECT="${CAPTIONSLOT_SLOTS_PER_OBJECT}" \
  CAPTIONSLOT_N_REGISTER="${CAPTIONSLOT_N_REGISTER}" \
  CAPTIONSLOT_CMD_LENGTH="${CAPTIONSLOT_CMD_LENGTH}" \
  CAPTIONSLOT_RECON_LOSS_WEIGHT="${CAPTIONSLOT_RECON_LOSS_WEIGHT}" \
  CAPTIONSLOT_MASK_BCE_LOSS_WEIGHT="${CAPTIONSLOT_MASK_BCE_LOSS_WEIGHT}" \
  CAPTIONSLOT_MASK_DICE_LOSS_WEIGHT="${CAPTIONSLOT_MASK_DICE_LOSS_WEIGHT}" \
  CAPTIONSLOT_CAPTION_LOSS_WEIGHT="${CAPTIONSLOT_CAPTION_LOSS_WEIGHT}" \
  CAPTIONSLOT_DIVERSITY_LOSS_WEIGHT="${CAPTIONSLOT_DIVERSITY_LOSS_WEIGHT}" \
  CAPTIONSLOT_TRAIN_LATENT_QUERIES="${CAPTIONSLOT_TRAIN_LATENT_QUERIES}" \
  CAPTIONSLOT_ATTENTION_USE_LAYERNORM="${CAPTIONSLOT_ATTENTION_USE_LAYERNORM}" \
  CAPTIONSLOT_ATTENTION_TEMPERATURE="${CAPTIONSLOT_ATTENTION_TEMPERATURE}" \
  CAPTIONSLOT_PRIOR_BIAS_SCALE="${CAPTIONSLOT_PRIOR_BIAS_SCALE}" \
  CAPTIONSLOT_ADD_CROSS_ATTENTION="${CAPTIONSLOT_ADD_CROSS_ATTENTION}" \
  CAPTIONSLOT_CROSS_ATTENTION_START_BLOCK="${CAPTIONSLOT_CROSS_ATTENTION_START_BLOCK}" \
  CAPTIONSLOT_CROSS_ATTENTION_EVERY_N_BLOCKS="${CAPTIONSLOT_CROSS_ATTENTION_EVERY_N_BLOCKS}" \
  CAPTIONSLOT_CROSS_ATTENTION_INCLUDE_REGISTERS="${CAPTIONSLOT_CROSS_ATTENTION_INCLUDE_REGISTERS}" \
  CAPTIONSLOT_USE_WSD_SCHEDULE="${CAPTIONSLOT_USE_WSD_SCHEDULE}" \
  CAPTIONSLOT_WSD_DECAY_FRACTION="${CAPTIONSLOT_WSD_DECAY_FRACTION}" \
  CAPTIONSLOT_USE_COSINE_MIN_LR_SCHEDULE="${CAPTIONSLOT_USE_COSINE_MIN_LR_SCHEDULE}" \
  CAPTIONSLOT_MIN_LR_RATIO="${CAPTIONSLOT_MIN_LR_RATIO}" \
  CAPTIONSLOT_EVAL_NUM_IMAGES="${CAPTIONSLOT_EVAL_NUM_IMAGES}" \
  CAPTIONSLOT_COCO_ROOT="${CAPTIONSLOT_COCO_ROOT}" \
  CAPTIONSLOT_DATASETS="${CAPTIONSLOT_DATASETS}" \
  CAPTIONSLOT_TRAIN_SPLITS="${CAPTIONSLOT_TRAIN_SPLITS}" \
  CAPTIONSLOT_EVAL_SPLITS="${CAPTIONSLOT_EVAL_SPLITS}" \
  CAPTIONSLOT_MIN_AREA="${CAPTIONSLOT_MIN_AREA}" \
  MAX_CAPTION_TOKENS="${MAX_CAPTION_TOKENS}" \
  MODEL_MAX_LENGTH="${MODEL_MAX_LENGTH}" \
  DIFFUSION_NORM_STATS_PATH="${DIFFUSION_NORM_STATS_PATH}" \
  bash "${SCRIPT_DIR}/train_aurora_stage1_objectprior_noxattn_recon.sh"
