#!/bin/bash
# Phase 1 v2: OLD success config (BCE + Dice via Tversky α=β=0.5) + improvements
#   Key restorations from OLD (proven 0.33 slot_iou):
#     - max_slots=24, slots_per_object=2
#     - mask_bce=0.5, mask_tversky(α=β=0.5)=1.0  (= Dice equivalent)
#     - train_latent_queries=True, DiT body frozen
#     - cosine schedule (NOT WSD — OLD's WSD was suboptimal)
#   Key improvements over OLD:
#     - attention_temperature=0.5  (OLD 1.0 → sharper sigmoid → mBO/FG-ARI ↑)
#     - mask_balanced_bce=True     (OLD False → break BCE plateau)
#     - cosine_min schedule        (OLD WSD → smoother late-stage decay)
#     - dual vision tower 1024+256 (OLD single 256 → richer features)
#     - recon_weight=0.5           (OLD 1.5 → slot focus, less recon competition)
#   Logging cleanup: CAM losses OFF → not logged (object_cam, register_cam = 0)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

OUTPUT_DIR="${OUTPUT_DIR:-/home/jovyan/AURORA/checkpoints/aurora_refcoco_phase1_oldconfig_v2_stage1_fp32}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-aurora_refcoco_phase1_oldconfig_v2_stage1_fp32}"
RESUME_FROM_CHECKPOINT="${RESUME_FROM_CHECKPOINT:-}"

# Batch / steps (OLD config: bs=16, accum=1, 40k steps)
PER_DEVICE_TRAIN_BATCH_SIZE="${PER_DEVICE_TRAIN_BATCH_SIZE:-16}"
PER_DEVICE_EVAL_BATCH_SIZE="${PER_DEVICE_EVAL_BATCH_SIZE:-4}"
GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS:-1}"
MAX_STEPS="${MAX_STEPS:-40000}"
EVAL_STEPS="${EVAL_STEPS:-2000}"
SAVE_STEPS="${SAVE_STEPS:-2000}"
LOGGING_STEPS="${LOGGING_STEPS:-20}"
DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS:-8}"
CAPTIONSLOT_EVAL_NUM_IMAGES="${CAPTIONSLOT_EVAL_NUM_IMAGES:-64}"

# LR
LEARNING_RATE="${LEARNING_RATE:-5e-5}"
DIFF_HEAD_LR="${DIFF_HEAD_LR:-3e-5}"
WARMUP_RATIO="${WARMUP_RATIO:-0.05}"
LR_SCHEDULER_TYPE="${LR_SCHEDULER_TYPE:-cosine}"
CAPTIONSLOT_USE_WSD_SCHEDULE="${CAPTIONSLOT_USE_WSD_SCHEDULE:-False}"
CAPTIONSLOT_USE_COSINE_MIN_LR_SCHEDULE="${CAPTIONSLOT_USE_COSINE_MIN_LR_SCHEDULE:-True}"
CAPTIONSLOT_MIN_LR_RATIO="${CAPTIONSLOT_MIN_LR_RATIO:-0.10}"

# Slot architecture (OLD-proven)
CAPTIONSLOT_MAX_SLOTS="${CAPTIONSLOT_MAX_SLOTS:-24}"
CAPTIONSLOT_SLOTS_PER_OBJECT="${CAPTIONSLOT_SLOTS_PER_OBJECT:-2}"
CAPTIONSLOT_N_REGISTER="${CAPTIONSLOT_N_REGISTER:-64}"

# >>> KEY IMPROVEMENT: sharper attention <<<
CAPTIONSLOT_ATTENTION_TEMPERATURE="${CAPTIONSLOT_ATTENTION_TEMPERATURE:-0.5}"
CAPTIONSLOT_ATTENTION_USE_LAYERNORM="${CAPTIONSLOT_ATTENTION_USE_LAYERNORM:-True}"

# >>> KEY IMPROVEMENT: BCE plateau fix <<<
CAPTIONSLOT_MASK_BALANCED_BCE="${CAPTIONSLOT_MASK_BALANCED_BCE:-True}"

# Loss weights (Phase 1: slot focus, recon as warmup-only)
CAPTIONSLOT_RECON_LOSS_WEIGHT="${CAPTIONSLOT_RECON_LOSS_WEIGHT:-0.5}"
CAPTIONSLOT_MASK_BCE_LOSS_WEIGHT="${CAPTIONSLOT_MASK_BCE_LOSS_WEIGHT:-0.5}"
CAPTIONSLOT_MASK_TVERSKY_LOSS_WEIGHT="${CAPTIONSLOT_MASK_TVERSKY_LOSS_WEIGHT:-1.0}"
CAPTIONSLOT_MASK_TVERSKY_ALPHA="${CAPTIONSLOT_MASK_TVERSKY_ALPHA:-0.5}"
CAPTIONSLOT_MASK_TVERSKY_BETA="${CAPTIONSLOT_MASK_TVERSKY_BETA:-0.5}"
# Legacy weight is shadowed by tversky if both set; keep 0 for clarity
CAPTIONSLOT_MASK_DICE_LOSS_WEIGHT="${CAPTIONSLOT_MASK_DICE_LOSS_WEIGHT:-0.0}"
# CAM supervision OFF (OLD didn't use it; logging suppressed when 0)
CAPTIONSLOT_OBJECT_CAM_LOSS_WEIGHT="${CAPTIONSLOT_OBJECT_CAM_LOSS_WEIGHT:-0.0}"
CAPTIONSLOT_REGISTER_CAM_LOSS_WEIGHT="${CAPTIONSLOT_REGISTER_CAM_LOSS_WEIGHT:-0.0}"

# Trainable groups (OLD-proven)
CAPTIONSLOT_TRAIN_LATENT_QUERIES="${CAPTIONSLOT_TRAIN_LATENT_QUERIES:-True}"
CAPTIONSLOT_LATENT_QUERY_LR="${CAPTIONSLOT_LATENT_QUERY_LR:-}"
CAPTIONSLOT_UNFREEZE_DIFF_HEAD_BODY="${CAPTIONSLOT_UNFREEZE_DIFF_HEAD_BODY:-False}"
CAPTIONSLOT_UNFREEZE_LLM_LAST_N_LAYERS="${CAPTIONSLOT_UNFREEZE_LLM_LAST_N_LAYERS:-0}"
CAPTIONSLOT_UNFREEZE_LLM_ATTN_ONLY="${CAPTIONSLOT_UNFREEZE_LLM_ATTN_ONLY:-True}"
CAPTIONSLOT_LLM_LR="${CAPTIONSLOT_LLM_LR:-}"

MAX_CAPTION_TOKENS="${MAX_CAPTION_TOKENS:-128}"
MODEL_MAX_LENGTH="${MODEL_MAX_LENGTH:-2048}"

# Cross-attention (OLD-proven)
CAPTIONSLOT_ADD_CROSS_ATTENTION="${CAPTIONSLOT_ADD_CROSS_ATTENTION:-True}"
CAPTIONSLOT_CROSS_ATTENTION_START_BLOCK="${CAPTIONSLOT_CROSS_ATTENTION_START_BLOCK:-8}"
CAPTIONSLOT_CROSS_ATTENTION_EVERY_N_BLOCKS="${CAPTIONSLOT_CROSS_ATTENTION_EVERY_N_BLOCKS:-4}"
CAPTIONSLOT_CROSS_ATTENTION_INCLUDE_REGISTERS="${CAPTIONSLOT_CROSS_ATTENTION_INCLUDE_REGISTERS:-True}"

TF32="${TF32:-True}"
BF16="${BF16:-False}"
REPORT_TO="${REPORT_TO:-wandb}"

# Best checkpoint: track slot quality
CAPTIONSLOT_SAVE_BEST_CHECKPOINT="${CAPTIONSLOT_SAVE_BEST_CHECKPOINT:-True}"
CAPTIONSLOT_BEST_METRIC_NAME="${CAPTIONSLOT_BEST_METRIC_NAME:-eval_object_soft_iou}"
CAPTIONSLOT_BEST_GREATER_IS_BETTER="${CAPTIONSLOT_BEST_GREATER_IS_BETTER:-True}"
CAPTIONSLOT_BEST_CHECKPOINT_SUBDIR="${CAPTIONSLOT_BEST_CHECKPOINT_SUBDIR:-best-checkpoint}"

env \
  OUTPUT_DIR="${OUTPUT_DIR}" \
  EXPERIMENT_NAME="${EXPERIMENT_NAME}" \
  RESUME_FROM_CHECKPOINT="${RESUME_FROM_CHECKPOINT}" \
  PER_DEVICE_TRAIN_BATCH_SIZE="${PER_DEVICE_TRAIN_BATCH_SIZE}" \
  PER_DEVICE_EVAL_BATCH_SIZE="${PER_DEVICE_EVAL_BATCH_SIZE}" \
  GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS}" \
  MAX_STEPS="${MAX_STEPS}" \
  EVAL_STEPS="${EVAL_STEPS}" \
  SAVE_STEPS="${SAVE_STEPS}" \
  LOGGING_STEPS="${LOGGING_STEPS}" \
  DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS}" \
  CAPTIONSLOT_EVAL_NUM_IMAGES="${CAPTIONSLOT_EVAL_NUM_IMAGES}" \
  LEARNING_RATE="${LEARNING_RATE}" \
  DIFF_HEAD_LR="${DIFF_HEAD_LR}" \
  WARMUP_RATIO="${WARMUP_RATIO}" \
  LR_SCHEDULER_TYPE="${LR_SCHEDULER_TYPE}" \
  CAPTIONSLOT_USE_WSD_SCHEDULE="${CAPTIONSLOT_USE_WSD_SCHEDULE}" \
  CAPTIONSLOT_USE_COSINE_MIN_LR_SCHEDULE="${CAPTIONSLOT_USE_COSINE_MIN_LR_SCHEDULE}" \
  CAPTIONSLOT_MIN_LR_RATIO="${CAPTIONSLOT_MIN_LR_RATIO}" \
  CAPTIONSLOT_MAX_SLOTS="${CAPTIONSLOT_MAX_SLOTS}" \
  CAPTIONSLOT_SLOTS_PER_OBJECT="${CAPTIONSLOT_SLOTS_PER_OBJECT}" \
  CAPTIONSLOT_N_REGISTER="${CAPTIONSLOT_N_REGISTER}" \
  CAPTIONSLOT_ATTENTION_TEMPERATURE="${CAPTIONSLOT_ATTENTION_TEMPERATURE}" \
  CAPTIONSLOT_ATTENTION_USE_LAYERNORM="${CAPTIONSLOT_ATTENTION_USE_LAYERNORM}" \
  CAPTIONSLOT_MASK_BALANCED_BCE="${CAPTIONSLOT_MASK_BALANCED_BCE}" \
  CAPTIONSLOT_RECON_LOSS_WEIGHT="${CAPTIONSLOT_RECON_LOSS_WEIGHT}" \
  CAPTIONSLOT_MASK_BCE_LOSS_WEIGHT="${CAPTIONSLOT_MASK_BCE_LOSS_WEIGHT}" \
  CAPTIONSLOT_MASK_DICE_LOSS_WEIGHT="${CAPTIONSLOT_MASK_DICE_LOSS_WEIGHT}" \
  CAPTIONSLOT_MASK_TVERSKY_LOSS_WEIGHT="${CAPTIONSLOT_MASK_TVERSKY_LOSS_WEIGHT}" \
  CAPTIONSLOT_MASK_TVERSKY_ALPHA="${CAPTIONSLOT_MASK_TVERSKY_ALPHA}" \
  CAPTIONSLOT_MASK_TVERSKY_BETA="${CAPTIONSLOT_MASK_TVERSKY_BETA}" \
  CAPTIONSLOT_OBJECT_CAM_LOSS_WEIGHT="${CAPTIONSLOT_OBJECT_CAM_LOSS_WEIGHT}" \
  CAPTIONSLOT_REGISTER_CAM_LOSS_WEIGHT="${CAPTIONSLOT_REGISTER_CAM_LOSS_WEIGHT}" \
  CAPTIONSLOT_TRAIN_LATENT_QUERIES="${CAPTIONSLOT_TRAIN_LATENT_QUERIES}" \
  CAPTIONSLOT_LATENT_QUERY_LR="${CAPTIONSLOT_LATENT_QUERY_LR}" \
  CAPTIONSLOT_UNFREEZE_DIFF_HEAD_BODY="${CAPTIONSLOT_UNFREEZE_DIFF_HEAD_BODY}" \
  CAPTIONSLOT_UNFREEZE_LLM_LAST_N_LAYERS="${CAPTIONSLOT_UNFREEZE_LLM_LAST_N_LAYERS}" \
  CAPTIONSLOT_UNFREEZE_LLM_ATTN_ONLY="${CAPTIONSLOT_UNFREEZE_LLM_ATTN_ONLY}" \
  CAPTIONSLOT_LLM_LR="${CAPTIONSLOT_LLM_LR}" \
  MAX_CAPTION_TOKENS="${MAX_CAPTION_TOKENS}" \
  MODEL_MAX_LENGTH="${MODEL_MAX_LENGTH}" \
  CAPTIONSLOT_ADD_CROSS_ATTENTION="${CAPTIONSLOT_ADD_CROSS_ATTENTION}" \
  CAPTIONSLOT_CROSS_ATTENTION_START_BLOCK="${CAPTIONSLOT_CROSS_ATTENTION_START_BLOCK}" \
  CAPTIONSLOT_CROSS_ATTENTION_EVERY_N_BLOCKS="${CAPTIONSLOT_CROSS_ATTENTION_EVERY_N_BLOCKS}" \
  CAPTIONSLOT_CROSS_ATTENTION_INCLUDE_REGISTERS="${CAPTIONSLOT_CROSS_ATTENTION_INCLUDE_REGISTERS}" \
  TF32="${TF32}" \
  BF16="${BF16}" \
  REPORT_TO="${REPORT_TO}" \
  CAPTIONSLOT_SAVE_BEST_CHECKPOINT="${CAPTIONSLOT_SAVE_BEST_CHECKPOINT}" \
  CAPTIONSLOT_BEST_METRIC_NAME="${CAPTIONSLOT_BEST_METRIC_NAME}" \
  CAPTIONSLOT_BEST_GREATER_IS_BETTER="${CAPTIONSLOT_BEST_GREATER_IS_BETTER}" \
  CAPTIONSLOT_BEST_CHECKPOINT_SUBDIR="${CAPTIONSLOT_BEST_CHECKPOINT_SUBDIR}" \
  bash "${SCRIPT_DIR}/train_aurora.sh"
