#!/bin/bash
# Single-phase stage1: 16 slots/object + DiT body unfrozen + NO LoRA on LLM
#   - Decompose image into object-level slot bundles + register tokens (rest)
#   - 16 slots per object with MEAN aggregation supervision (per prof)
#   - DiT lr fixed at 1e-4 (after warmup, no decay)
#   - main lr fixed at 5e-5 (consistency with DiT — all groups constant_with_warmup)
#   - latent_queries trainable (no Phase1/2 split, single phase)
#   - LLM completely frozen (this variant: no LoRA)
#   - Mask supervision: balanced BCE + Tversky (alpha=beta=0.5 = Dice)
#   - Best metric: eval_object_soft_iou (segmentation proxy)
#
# Run on a single GPU (e.g. CUDA_VISIBLE_DEVICES=0)
# Pair with the LoRA variant on a different GPU for parallel comparison.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

OUTPUT_DIR="${OUTPUT_DIR:-/home/jovyan/AURORA/checkpoints/aurora_refcoco_singlephase_slot16_noLora_stage1_fp32}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-aurora_refcoco_singlephase_slot16_noLora_stage1_fp32}"
RESUME_FROM_CHECKPOINT="${RESUME_FROM_CHECKPOINT:-}"

# >>> Single GPU <<<
NUM_GPUS="${NUM_GPUS:-1}"
MASTER_PORT="${MASTER_PORT:-29501}"

# Batch / accum (effective batch=32 with 1 GPU × 8 × 4)
PER_DEVICE_TRAIN_BATCH_SIZE="${PER_DEVICE_TRAIN_BATCH_SIZE:-8}"
PER_DEVICE_EVAL_BATCH_SIZE="${PER_DEVICE_EVAL_BATCH_SIZE:-4}"
GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS:-4}"
MAX_STEPS="${MAX_STEPS:-10000}"
EVAL_STEPS="${EVAL_STEPS:-1000}"
SAVE_STEPS="${SAVE_STEPS:-1000}"
LOGGING_STEPS="${LOGGING_STEPS:-20}"
DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS:-8}"
CAPTIONSLOT_EVAL_NUM_IMAGES="${CAPTIONSLOT_EVAL_NUM_IMAGES:-64}"

# >>> LR (constant_with_warmup for ALL groups) <<<
LEARNING_RATE="${LEARNING_RATE:-5e-5}"
DIFF_HEAD_LR="${DIFF_HEAD_LR:-1e-4}"            # DiT fixed at 1e-4 (after warmup)
WARMUP_RATIO="${WARMUP_RATIO:-0.10}"             # 10% warmup → DiT noise damage protection
LR_SCHEDULER_TYPE="${LR_SCHEDULER_TYPE:-constant_with_warmup}"
CAPTIONSLOT_USE_WSD_SCHEDULE="${CAPTIONSLOT_USE_WSD_SCHEDULE:-False}"
CAPTIONSLOT_USE_COSINE_MIN_LR_SCHEDULE="${CAPTIONSLOT_USE_COSINE_MIN_LR_SCHEDULE:-False}"

# >>> Slot architecture: 16 slots/object × 12 objects max = 192 slots total <<<
CAPTIONSLOT_MAX_SLOTS="${CAPTIONSLOT_MAX_SLOTS:-192}"
CAPTIONSLOT_SLOTS_PER_OBJECT="${CAPTIONSLOT_SLOTS_PER_OBJECT:-16}"
CAPTIONSLOT_N_REGISTER="${CAPTIONSLOT_N_REGISTER:-64}"

# Attention setup
CAPTIONSLOT_ATTENTION_TEMPERATURE="${CAPTIONSLOT_ATTENTION_TEMPERATURE:-0.5}"
CAPTIONSLOT_ATTENTION_USE_LAYERNORM="${CAPTIONSLOT_ATTENTION_USE_LAYERNORM:-True}"
CAPTIONSLOT_MASK_BALANCED_BCE="${CAPTIONSLOT_MASK_BALANCED_BCE:-True}"

# Loss weights (single-phase: balanced — slot losses 1.5 vs recon 1.0)
CAPTIONSLOT_RECON_LOSS_WEIGHT="${CAPTIONSLOT_RECON_LOSS_WEIGHT:-1.0}"
CAPTIONSLOT_MASK_BCE_LOSS_WEIGHT="${CAPTIONSLOT_MASK_BCE_LOSS_WEIGHT:-0.5}"
CAPTIONSLOT_MASK_TVERSKY_LOSS_WEIGHT="${CAPTIONSLOT_MASK_TVERSKY_LOSS_WEIGHT:-1.0}"
CAPTIONSLOT_MASK_TVERSKY_ALPHA="${CAPTIONSLOT_MASK_TVERSKY_ALPHA:-0.5}"
CAPTIONSLOT_MASK_TVERSKY_BETA="${CAPTIONSLOT_MASK_TVERSKY_BETA:-0.5}"
CAPTIONSLOT_MASK_DICE_LOSS_WEIGHT="${CAPTIONSLOT_MASK_DICE_LOSS_WEIGHT:-0.0}"
CAPTIONSLOT_OBJECT_CAM_LOSS_WEIGHT="${CAPTIONSLOT_OBJECT_CAM_LOSS_WEIGHT:-0.0}"
CAPTIONSLOT_REGISTER_CAM_LOSS_WEIGHT="${CAPTIONSLOT_REGISTER_CAM_LOSS_WEIGHT:-0.0}"

# Trainable groups
CAPTIONSLOT_TRAIN_LATENT_QUERIES="${CAPTIONSLOT_TRAIN_LATENT_QUERIES:-True}"
CAPTIONSLOT_LATENT_QUERY_LR="${CAPTIONSLOT_LATENT_QUERY_LR:-}"
CAPTIONSLOT_UNFREEZE_DIFF_HEAD_BODY="${CAPTIONSLOT_UNFREEZE_DIFF_HEAD_BODY:-False}"
CAPTIONSLOT_UNFREEZE_LLM_LAST_N_LAYERS="${CAPTIONSLOT_UNFREEZE_LLM_LAST_N_LAYERS:-0}"
CAPTIONSLOT_UNFREEZE_LLM_ATTN_ONLY="${CAPTIONSLOT_UNFREEZE_LLM_ATTN_ONLY:-True}"
CAPTIONSLOT_LLM_LR="${CAPTIONSLOT_LLM_LR:-}"

# >>> NO LoRA <<<
CAPTIONSLOT_LORA_ENABLE="${CAPTIONSLOT_LORA_ENABLE:-False}"

MAX_CAPTION_TOKENS="${MAX_CAPTION_TOKENS:-128}"
MODEL_MAX_LENGTH="${MODEL_MAX_LENGTH:-2048}"

CAPTIONSLOT_ADD_CROSS_ATTENTION="${CAPTIONSLOT_ADD_CROSS_ATTENTION:-True}"
CAPTIONSLOT_CROSS_ATTENTION_START_BLOCK="${CAPTIONSLOT_CROSS_ATTENTION_START_BLOCK:-8}"
CAPTIONSLOT_CROSS_ATTENTION_EVERY_N_BLOCKS="${CAPTIONSLOT_CROSS_ATTENTION_EVERY_N_BLOCKS:-4}"
CAPTIONSLOT_CROSS_ATTENTION_INCLUDE_REGISTERS="${CAPTIONSLOT_CROSS_ATTENTION_INCLUDE_REGISTERS:-True}"

TF32="${TF32:-True}"
BF16="${BF16:-False}"
REPORT_TO="${REPORT_TO:-wandb}"

# Best checkpoint: track segmentation quality (eval_object_soft_iou is downstream-relevant)
CAPTIONSLOT_SAVE_BEST_CHECKPOINT="${CAPTIONSLOT_SAVE_BEST_CHECKPOINT:-True}"
CAPTIONSLOT_BEST_METRIC_NAME="${CAPTIONSLOT_BEST_METRIC_NAME:-eval_object_soft_iou}"
CAPTIONSLOT_BEST_GREATER_IS_BETTER="${CAPTIONSLOT_BEST_GREATER_IS_BETTER:-True}"
CAPTIONSLOT_BEST_CHECKPOINT_SUBDIR="${CAPTIONSLOT_BEST_CHECKPOINT_SUBDIR:-best-checkpoint}"

env \
  OUTPUT_DIR="${OUTPUT_DIR}" \
  EXPERIMENT_NAME="${EXPERIMENT_NAME}" \
  RESUME_FROM_CHECKPOINT="${RESUME_FROM_CHECKPOINT}" \
  NUM_GPUS="${NUM_GPUS}" \
  MASTER_PORT="${MASTER_PORT}" \
  PER_DEVICE_TRAIN_BATCH_SIZE="${PER_DEVICE_TRAIN_BATCH_SIZE}" \
  PER_DEVICE_EVAL_BATCH_SIZE="${PER_DEVICE_EVAL_BATCH_SIZE}" \
  GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS}" \
  MAX_STEPS="${MAX_STEPS}" \
  EVAL_STEPS="${EVAL_STEPS}" \
  SAVE_STEPS="${SAVE_STEPS}" \
  LOGGING_STEPS="${LOGGING_STEPS}" \
  DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS}" \
  CAPTIONSLOT_EVAL_NUM_IMAGES="${CAPTIONSLOT_EVAL_NUM_IMAGES}" \
  LEARNING_RATE="${LEARNING_RATE}" \
  DIFF_HEAD_LR="${DIFF_HEAD_LR}" \
  WARMUP_RATIO="${WARMUP_RATIO}" \
  LR_SCHEDULER_TYPE="${LR_SCHEDULER_TYPE}" \
  CAPTIONSLOT_USE_WSD_SCHEDULE="${CAPTIONSLOT_USE_WSD_SCHEDULE}" \
  CAPTIONSLOT_USE_COSINE_MIN_LR_SCHEDULE="${CAPTIONSLOT_USE_COSINE_MIN_LR_SCHEDULE}" \
  CAPTIONSLOT_MAX_SLOTS="${CAPTIONSLOT_MAX_SLOTS}" \
  CAPTIONSLOT_SLOTS_PER_OBJECT="${CAPTIONSLOT_SLOTS_PER_OBJECT}" \
  CAPTIONSLOT_N_REGISTER="${CAPTIONSLOT_N_REGISTER}" \
  CAPTIONSLOT_ATTENTION_TEMPERATURE="${CAPTIONSLOT_ATTENTION_TEMPERATURE}" \
  CAPTIONSLOT_ATTENTION_USE_LAYERNORM="${CAPTIONSLOT_ATTENTION_USE_LAYERNORM}" \
  CAPTIONSLOT_MASK_BALANCED_BCE="${CAPTIONSLOT_MASK_BALANCED_BCE}" \
  CAPTIONSLOT_RECON_LOSS_WEIGHT="${CAPTIONSLOT_RECON_LOSS_WEIGHT}" \
  CAPTIONSLOT_MASK_BCE_LOSS_WEIGHT="${CAPTIONSLOT_MASK_BCE_LOSS_WEIGHT}" \
  CAPTIONSLOT_MASK_DICE_LOSS_WEIGHT="${CAPTIONSLOT_MASK_DICE_LOSS_WEIGHT}" \
  CAPTIONSLOT_MASK_TVERSKY_LOSS_WEIGHT="${CAPTIONSLOT_MASK_TVERSKY_LOSS_WEIGHT}" \
  CAPTIONSLOT_MASK_TVERSKY_ALPHA="${CAPTIONSLOT_MASK_TVERSKY_ALPHA}" \
  CAPTIONSLOT_MASK_TVERSKY_BETA="${CAPTIONSLOT_MASK_TVERSKY_BETA}" \
  CAPTIONSLOT_OBJECT_CAM_LOSS_WEIGHT="${CAPTIONSLOT_OBJECT_CAM_LOSS_WEIGHT}" \
  CAPTIONSLOT_REGISTER_CAM_LOSS_WEIGHT="${CAPTIONSLOT_REGISTER_CAM_LOSS_WEIGHT}" \
  CAPTIONSLOT_TRAIN_LATENT_QUERIES="${CAPTIONSLOT_TRAIN_LATENT_QUERIES}" \
  CAPTIONSLOT_LATENT_QUERY_LR="${CAPTIONSLOT_LATENT_QUERY_LR}" \
  CAPTIONSLOT_UNFREEZE_DIFF_HEAD_BODY="${CAPTIONSLOT_UNFREEZE_DIFF_HEAD_BODY}" \
  CAPTIONSLOT_UNFREEZE_LLM_LAST_N_LAYERS="${CAPTIONSLOT_UNFREEZE_LLM_LAST_N_LAYERS}" \
  CAPTIONSLOT_UNFREEZE_LLM_ATTN_ONLY="${CAPTIONSLOT_UNFREEZE_LLM_ATTN_ONLY}" \
  CAPTIONSLOT_LLM_LR="${CAPTIONSLOT_LLM_LR}" \
  CAPTIONSLOT_LORA_ENABLE="${CAPTIONSLOT_LORA_ENABLE}" \
  MAX_CAPTION_TOKENS="${MAX_CAPTION_TOKENS}" \
  MODEL_MAX_LENGTH="${MODEL_MAX_LENGTH}" \
  CAPTIONSLOT_ADD_CROSS_ATTENTION="${CAPTIONSLOT_ADD_CROSS_ATTENTION}" \
  CAPTIONSLOT_CROSS_ATTENTION_START_BLOCK="${CAPTIONSLOT_CROSS_ATTENTION_START_BLOCK}" \
  CAPTIONSLOT_CROSS_ATTENTION_EVERY_N_BLOCKS="${CAPTIONSLOT_CROSS_ATTENTION_EVERY_N_BLOCKS}" \
  CAPTIONSLOT_CROSS_ATTENTION_INCLUDE_REGISTERS="${CAPTIONSLOT_CROSS_ATTENTION_INCLUDE_REGISTERS}" \
  TF32="${TF32}" \
  BF16="${BF16}" \
  REPORT_TO="${REPORT_TO}" \
  CAPTIONSLOT_SAVE_BEST_CHECKPOINT="${CAPTIONSLOT_SAVE_BEST_CHECKPOINT}" \
  CAPTIONSLOT_BEST_METRIC_NAME="${CAPTIONSLOT_BEST_METRIC_NAME}" \
  CAPTIONSLOT_BEST_GREATER_IS_BETTER="${CAPTIONSLOT_BEST_GREATER_IS_BETTER}" \
  CAPTIONSLOT_BEST_CHECKPOINT_SUBDIR="${CAPTIONSLOT_BEST_CHECKPOINT_SUBDIR}" \
  bash "${SCRIPT_DIR}/train_aurora.sh"
