#!/bin/bash
# Experiment A: 32 slots/object (max_slots=384=12*32), recon_loss_weight=1.5
#   - Increased from 16→32 slots per object, same 12 objects max (384/32)
#   - recon_loss_weight raised to 1.5 for FID improvement
#   - MASTER_PORT=29503 (no conflict with slot16 on 29502)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

OUTPUT_DIR="${OUTPUT_DIR:-/home/jovyan/AURORA/checkpoints/aurora_refcoco_singlephase_slot32_lora_stage1_fp32}"
EXPERIMENT_NAME="${EXPERIMENT_NAME:-aurora_refcoco_singlephase_slot32_lora_stage1_fp32}"
RESUME_FROM_CHECKPOINT="${RESUME_FROM_CHECKPOINT:-}"

# >>> Single GPU (different MASTER_PORT from no-LoRA variant!) <<<
NUM_GPUS="${NUM_GPUS:-1}"
MASTER_PORT="${MASTER_PORT:-29503}"

PER_DEVICE_TRAIN_BATCH_SIZE="${PER_DEVICE_TRAIN_BATCH_SIZE:-8}"
PER_DEVICE_EVAL_BATCH_SIZE="${PER_DEVICE_EVAL_BATCH_SIZE:-4}"
GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS:-4}"
MAX_STEPS="${MAX_STEPS:-10000}"
EVAL_STEPS="${EVAL_STEPS:-1000}"
SAVE_STEPS="${SAVE_STEPS:-1000}"
LOGGING_STEPS="${LOGGING_STEPS:-20}"
DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS:-8}"
CAPTIONSLOT_EVAL_NUM_IMAGES="${CAPTIONSLOT_EVAL_NUM_IMAGES:-64}"

LEARNING_RATE="${LEARNING_RATE:-5e-5}"
DIFF_HEAD_LR="${DIFF_HEAD_LR:-1e-4}"
WARMUP_RATIO="${WARMUP_RATIO:-0.10}"
LR_SCHEDULER_TYPE="${LR_SCHEDULER_TYPE:-constant_with_warmup}"
CAPTIONSLOT_USE_WSD_SCHEDULE="${CAPTIONSLOT_USE_WSD_SCHEDULE:-False}"
CAPTIONSLOT_USE_COSINE_MIN_LR_SCHEDULE="${CAPTIONSLOT_USE_COSINE_MIN_LR_SCHEDULE:-False}"

CAPTIONSLOT_MAX_SLOTS="${CAPTIONSLOT_MAX_SLOTS:-384}"
CAPTIONSLOT_SLOTS_PER_OBJECT="${CAPTIONSLOT_SLOTS_PER_OBJECT:-32}"
CAPTIONSLOT_N_REGISTER="${CAPTIONSLOT_N_REGISTER:-64}"

CAPTIONSLOT_ATTENTION_TEMPERATURE="${CAPTIONSLOT_ATTENTION_TEMPERATURE:-0.5}"
CAPTIONSLOT_ATTENTION_USE_LAYERNORM="${CAPTIONSLOT_ATTENTION_USE_LAYERNORM:-True}"
CAPTIONSLOT_MASK_BALANCED_BCE="${CAPTIONSLOT_MASK_BALANCED_BCE:-True}"

CAPTIONSLOT_RECON_LOSS_WEIGHT="${CAPTIONSLOT_RECON_LOSS_WEIGHT:-1.5}"
CAPTIONSLOT_MASK_BCE_LOSS_WEIGHT="${CAPTIONSLOT_MASK_BCE_LOSS_WEIGHT:-0.5}"
CAPTIONSLOT_MASK_TVERSKY_LOSS_WEIGHT="${CAPTIONSLOT_MASK_TVERSKY_LOSS_WEIGHT:-1.0}"
CAPTIONSLOT_MASK_TVERSKY_ALPHA="${CAPTIONSLOT_MASK_TVERSKY_ALPHA:-0.5}"
CAPTIONSLOT_MASK_TVERSKY_BETA="${CAPTIONSLOT_MASK_TVERSKY_BETA:-0.5}"
CAPTIONSLOT_MASK_DICE_LOSS_WEIGHT="${CAPTIONSLOT_MASK_DICE_LOSS_WEIGHT:-0.0}"
CAPTIONSLOT_OBJECT_CAM_LOSS_WEIGHT="${CAPTIONSLOT_OBJECT_CAM_LOSS_WEIGHT:-0.0}"
CAPTIONSLOT_REGISTER_CAM_LOSS_WEIGHT="${CAPTIONSLOT_REGISTER_CAM_LOSS_WEIGHT:-0.0}"

CAPTIONSLOT_TRAIN_LATENT_QUERIES="${CAPTIONSLOT_TRAIN_LATENT_QUERIES:-True}"
CAPTIONSLOT_LATENT_QUERY_LR="${CAPTIONSLOT_LATENT_QUERY_LR:-}"
CAPTIONSLOT_UNFREEZE_DIFF_HEAD_BODY="${CAPTIONSLOT_UNFREEZE_DIFF_HEAD_BODY:-False}"
CAPTIONSLOT_UNFREEZE_LLM_LAST_N_LAYERS="${CAPTIONSLOT_UNFREEZE_LLM_LAST_N_LAYERS:-0}"
CAPTIONSLOT_UNFREEZE_LLM_ATTN_ONLY="${CAPTIONSLOT_UNFREEZE_LLM_ATTN_ONLY:-True}"

# >>> LoRA on LLM attention <<<
CAPTIONSLOT_LORA_ENABLE="${CAPTIONSLOT_LORA_ENABLE:-True}"
CAPTIONSLOT_LORA_R="${CAPTIONSLOT_LORA_R:-16}"
CAPTIONSLOT_LORA_ALPHA="${CAPTIONSLOT_LORA_ALPHA:-32}"
CAPTIONSLOT_LORA_DROPOUT="${CAPTIONSLOT_LORA_DROPOUT:-0.05}"
CAPTIONSLOT_LORA_TARGET_MODULES="${CAPTIONSLOT_LORA_TARGET_MODULES:-q_proj,k_proj,v_proj,o_proj}"
CAPTIONSLOT_LLM_LR="${CAPTIONSLOT_LLM_LR:-1e-4}"

MAX_CAPTION_TOKENS="${MAX_CAPTION_TOKENS:-128}"
MODEL_MAX_LENGTH="${MODEL_MAX_LENGTH:-2048}"

CAPTIONSLOT_ADD_CROSS_ATTENTION="${CAPTIONSLOT_ADD_CROSS_ATTENTION:-True}"
CAPTIONSLOT_CROSS_ATTENTION_START_BLOCK="${CAPTIONSLOT_CROSS_ATTENTION_START_BLOCK:-8}"
CAPTIONSLOT_CROSS_ATTENTION_EVERY_N_BLOCKS="${CAPTIONSLOT_CROSS_ATTENTION_EVERY_N_BLOCKS:-4}"
CAPTIONSLOT_CROSS_ATTENTION_INCLUDE_REGISTERS="${CAPTIONSLOT_CROSS_ATTENTION_INCLUDE_REGISTERS:-True}"

TF32="${TF32:-True}"
BF16="${BF16:-False}"
REPORT_TO="${REPORT_TO:-wandb}"

CAPTIONSLOT_SAVE_BEST_CHECKPOINT="${CAPTIONSLOT_SAVE_BEST_CHECKPOINT:-True}"
CAPTIONSLOT_BEST_METRIC_NAME="${CAPTIONSLOT_BEST_METRIC_NAME:-eval_object_soft_iou}"
CAPTIONSLOT_BEST_GREATER_IS_BETTER="${CAPTIONSLOT_BEST_GREATER_IS_BETTER:-True}"
CAPTIONSLOT_BEST_CHECKPOINT_SUBDIR="${CAPTIONSLOT_BEST_CHECKPOINT_SUBDIR:-best-checkpoint}"

env \
  OUTPUT_DIR="${OUTPUT_DIR}" \
  EXPERIMENT_NAME="${EXPERIMENT_NAME}" \
  RESUME_FROM_CHECKPOINT="${RESUME_FROM_CHECKPOINT}" \
  NUM_GPUS="${NUM_GPUS}" \
  MASTER_PORT="${MASTER_PORT}" \
  PER_DEVICE_TRAIN_BATCH_SIZE="${PER_DEVICE_TRAIN_BATCH_SIZE}" \
  PER_DEVICE_EVAL_BATCH_SIZE="${PER_DEVICE_EVAL_BATCH_SIZE}" \
  GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS}" \
  MAX_STEPS="${MAX_STEPS}" \
  EVAL_STEPS="${EVAL_STEPS}" \
  SAVE_STEPS="${SAVE_STEPS}" \
  LOGGING_STEPS="${LOGGING_STEPS}" \
  DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS}" \
  CAPTIONSLOT_EVAL_NUM_IMAGES="${CAPTIONSLOT_EVAL_NUM_IMAGES}" \
  LEARNING_RATE="${LEARNING_RATE}" \
  DIFF_HEAD_LR="${DIFF_HEAD_LR}" \
  WARMUP_RATIO="${WARMUP_RATIO}" \
  LR_SCHEDULER_TYPE="${LR_SCHEDULER_TYPE}" \
  CAPTIONSLOT_USE_WSD_SCHEDULE="${CAPTIONSLOT_USE_WSD_SCHEDULE}" \
  CAPTIONSLOT_USE_COSINE_MIN_LR_SCHEDULE="${CAPTIONSLOT_USE_COSINE_MIN_LR_SCHEDULE}" \
  CAPTIONSLOT_MAX_SLOTS="${CAPTIONSLOT_MAX_SLOTS}" \
  CAPTIONSLOT_SLOTS_PER_OBJECT="${CAPTIONSLOT_SLOTS_PER_OBJECT}" \
  CAPTIONSLOT_N_REGISTER="${CAPTIONSLOT_N_REGISTER}" \
  CAPTIONSLOT_ATTENTION_TEMPERATURE="${CAPTIONSLOT_ATTENTION_TEMPERATURE}" \
  CAPTIONSLOT_ATTENTION_USE_LAYERNORM="${CAPTIONSLOT_ATTENTION_USE_LAYERNORM}" \
  CAPTIONSLOT_MASK_BALANCED_BCE="${CAPTIONSLOT_MASK_BALANCED_BCE}" \
  CAPTIONSLOT_MASK_MERGE_MODE="${CAPTIONSLOT_MASK_MERGE_MODE:-mean}" \
  CAPTIONSLOT_RECON_LOSS_WEIGHT="${CAPTIONSLOT_RECON_LOSS_WEIGHT}" \
  CAPTIONSLOT_MASK_BCE_LOSS_WEIGHT="${CAPTIONSLOT_MASK_BCE_LOSS_WEIGHT}" \
  CAPTIONSLOT_MASK_DICE_LOSS_WEIGHT="${CAPTIONSLOT_MASK_DICE_LOSS_WEIGHT}" \
  CAPTIONSLOT_MASK_TVERSKY_LOSS_WEIGHT="${CAPTIONSLOT_MASK_TVERSKY_LOSS_WEIGHT}" \
  CAPTIONSLOT_MASK_TVERSKY_ALPHA="${CAPTIONSLOT_MASK_TVERSKY_ALPHA}" \
  CAPTIONSLOT_MASK_TVERSKY_BETA="${CAPTIONSLOT_MASK_TVERSKY_BETA}" \
  CAPTIONSLOT_OBJECT_CAM_LOSS_WEIGHT="${CAPTIONSLOT_OBJECT_CAM_LOSS_WEIGHT}" \
  CAPTIONSLOT_REGISTER_CAM_LOSS_WEIGHT="${CAPTIONSLOT_REGISTER_CAM_LOSS_WEIGHT}" \
  CAPTIONSLOT_TRAIN_LATENT_QUERIES="${CAPTIONSLOT_TRAIN_LATENT_QUERIES}" \
  CAPTIONSLOT_LATENT_QUERY_LR="${CAPTIONSLOT_LATENT_QUERY_LR}" \
  CAPTIONSLOT_UNFREEZE_DIFF_HEAD_BODY="${CAPTIONSLOT_UNFREEZE_DIFF_HEAD_BODY}" \
  CAPTIONSLOT_UNFREEZE_LLM_LAST_N_LAYERS="${CAPTIONSLOT_UNFREEZE_LLM_LAST_N_LAYERS}" \
  CAPTIONSLOT_UNFREEZE_LLM_ATTN_ONLY="${CAPTIONSLOT_UNFREEZE_LLM_ATTN_ONLY}" \
  CAPTIONSLOT_LLM_LR="${CAPTIONSLOT_LLM_LR}" \
  CAPTIONSLOT_LORA_ENABLE="${CAPTIONSLOT_LORA_ENABLE}" \
  CAPTIONSLOT_LORA_R="${CAPTIONSLOT_LORA_R}" \
  CAPTIONSLOT_LORA_ALPHA="${CAPTIONSLOT_LORA_ALPHA}" \
  CAPTIONSLOT_LORA_DROPOUT="${CAPTIONSLOT_LORA_DROPOUT}" \
  CAPTIONSLOT_LORA_TARGET_MODULES="${CAPTIONSLOT_LORA_TARGET_MODULES}" \
  MAX_CAPTION_TOKENS="${MAX_CAPTION_TOKENS}" \
  MODEL_MAX_LENGTH="${MODEL_MAX_LENGTH}" \
  CAPTIONSLOT_ADD_CROSS_ATTENTION="${CAPTIONSLOT_ADD_CROSS_ATTENTION}" \
  CAPTIONSLOT_CROSS_ATTENTION_START_BLOCK="${CAPTIONSLOT_CROSS_ATTENTION_START_BLOCK}" \
  CAPTIONSLOT_CROSS_ATTENTION_EVERY_N_BLOCKS="${CAPTIONSLOT_CROSS_ATTENTION_EVERY_N_BLOCKS}" \
  CAPTIONSLOT_CROSS_ATTENTION_INCLUDE_REGISTERS="${CAPTIONSLOT_CROSS_ATTENTION_INCLUDE_REGISTERS}" \
  TF32="${TF32}" \
  BF16="${BF16}" \
  REPORT_TO="${REPORT_TO}" \
  CAPTIONSLOT_SAVE_BEST_CHECKPOINT="${CAPTIONSLOT_SAVE_BEST_CHECKPOINT}" \
  CAPTIONSLOT_BEST_METRIC_NAME="${CAPTIONSLOT_BEST_METRIC_NAME}" \
  CAPTIONSLOT_BEST_GREATER_IS_BETTER="${CAPTIONSLOT_BEST_GREATER_IS_BETTER}" \
  CAPTIONSLOT_BEST_CHECKPOINT_SUBDIR="${CAPTIONSLOT_BEST_CHECKPOINT_SUBDIR}" \
  bash "${SCRIPT_DIR}/train_aurora.sh"
